spring:
  application:
    name: SetuApi
  datasource:
    url: jdbc:mysql://sql.cybersigmacs.in:3306/sigmaverify
    username: stagingserver
    password: cyberdb@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090

ongrid:
  secret-key: Nouwg6Ac2uZKYroemll1BPwW1G9URQiT
  api:
    endpoints:
      digilocker-init: https://api.gridlines.io/digilocker/init
      digilocker-issued-files: https://api.gridlines.io/digilocker/issued-files
      digilocker-issued-file: https://api.gridlines.io/digilocker/issued-file

invincible:
  client-id: b50c189fc515698e812eca9268f106a7:82f9e33759057b7a64268b87ad621c2d
  secret-key: njaohblcbgfIMgoOCtZDbVmXyqZx5K6utS4dDr8SbxDhs07EFfu3vxxaHhxk7cPRn
  api:
    endpoints:
      aadhaar: https://api.emptra.com/emptra/aadharVerification
      pan: https://api.emptra.com/fetchPanDetails
      bank-account: https://api.invincibleocean.com/invincible/bankAccountValidation/v1
      court-check: https://api.invincibleocean.com/invincible/courtCheckByCnr
      digilocker-init: https://api.emptra.com/initializeDigilockerV1
      digilocker-eAadhaar: https://api.emptra.com/eAadhaar
      digilocker-allDocuments: https://api.emptra.com/allIssuedFiles


token: EyjkaABJxOs5evsQFfxn02YNoqiha9ZOhnFDDccV7PhxcqHe2WPhU3hRHz6G6u9pfUF0Sb6SMy0A+0RlHBsW5yhwIuUo1n8c/zMUUbaSnULZioUlBIR6Cj6hlA7O8U/h2jmbL98D11RH4p5Pl8d4pI7wijDBP6xAnfjLwF2UlgqscWLKXyG4Vc28J0KVXsp2XXZ60AuyX/kNxvLXOQ1Ls8F/vy6+FFKU7E6roQ==%

email: tech@cybersigmassist.com