spring:
  application:
    name: SetuApi
  datasource:
    url: jdbc:mysql://sql.cybersigmacs.in:3306/sigmaverify
    username: stagingserver
    password: cyberdb@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090

invincible:
  client-id: 0f0cd3bcaec7525d68575c9b8a437a33:6f94fde5c3ec6b943629f8f3ef1187bb
  secret-key: IAj8ByiwOhk4RbrGVXJAuxQ0nMlJt8ohpp6dPn2sTAmrIqjrI1HABq8lQXPxICvEA
  api:
    endpoints:
      aadhaar: https://api.emptra.com/emptra/aadharVerification
      pan: https://api.emptra.com/fetchPanDetails

token: EyjkaABJxOs5evsQFfxn02YNoqiha9ZOhnFDDccV7PhxcqHe2WPhU3hRHz6G6u9pfUF0Sb6SMy0A+0RlHBsW5yhwIuUo1n8c/zMUUbaSnULZioUlBIR6Cj6hlA7O8U/h2jmbL98D11RH4p5Pl8d4pI7wijDBP6xAnfjLwF2UlgqscWLKXyG4Vc28J0KVXsp2XXZ60AuyX/kNxvLXOQ1Ls8F/vy6+FFKU7E6roQ==%

email: tech@cybersigmassist.com