spring:
  application:
    name: SetuApi
  datasource:
    url: jdbc:mysql://sql.cybersigmacs.in:3306/sigmaverify
    username: stagingserver
    password: cyberdb@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090

invincible:
  client-id: 80858af9ab44059cf328c1f033f074c6:36e8d5d79a44cadc7db0860fc516951b
  secret-key: 0gYNwBflL304HeRcdygWHlH6FmwbBEJC7VJ5ffPehDYKNWRgB7PfY6n6mP6zLfjhy
  api:
    endpoints:
      aadhaar: https://api.emptra.com/emptra/aadharVerification
      pan: https://api.emptra.com/fetchPanDetails

token: EyjkaABJxOs5evsQFfxn02YNoqiha9ZOhnFDDccV7PhxcqHe2WPhU3hRHz6G6u9pfUF0Sb6SMy0A+0RlHBsW5yhwIuUo1n8c/zMUUbaSnULZioUlBIR6Cj6hlA7O8U/h2jmbL98D11RH4p5Pl8d4pI7wijDBP6xAnfjLwF2UlgqscWLKXyG4Vc28J0KVXsp2XXZ60AuyX/kNxvLXOQ1Ls8F/vy6+FFKU7E6roQ==%

email: tech@cybersigmassist.com